### PR TITLE
Adding some information on the Workflow Run trigger

### PR DESCRIPTION
**Pull request by gs-emp**
Adding information about when the workflow_run triggers - this should be helpful for people who don't know it will only run in the default branch

### CODE REVIEW

**Comment by int128** [comment]
Sorry, does it mean the following considerations?

- A workflow of `workflow_run` is triggered for any event.
- A workflow of `workflow_run` is evaluated in the default branch. For changing the options of this action, we need to change the default branch.

**Comment by gs-emp** [comment]
Mainly that the workflow_run trigger is only evaluated from the default branch. You can specify what branches and such. 

I think for people when they add it to their repo may be confused by the fact that it won't trigger in a pullrequest or in a different branch.

So for example:
- I add this in my feature/datadog-metrics branch for repo X
- I make a pull request and am not sure why the trigger is not happening.

**Comment by gs-emp** [comment]
Not sure if my wording in the pr is great let me know at @int128

**Comment by gs-emp** [comment]
Gonna close this as we aren't using this anymore and clearing up my repos

**Pull request closed without merging**
